### ISSUE TITLE
Impossible to use a custom storage

### ISSUE THREAD

**Issue by xanderim** [just-work/django-sitemap-generate#32]
**type**: bug
**version**: 0.4.0
**description**:
1. SitemapGenerator init method accepts **storage: Optional[Storage]** instance but further in the code instead of using this instance, it tries to import it. Which is OK if you want to use defaults.SITEMAP_STORAGE but doesn't work when you pass custom storage objects. It was working on version 0.2.1.
```
storage = storage or defaults.SITEMAP_STORAGE
self.storage = import_string(storage)
```

2. If I try to use
`SITEMAP_STORAGE = 'testproject.testapp.storage.SitemapStorage'`
I will get 

> exists() missing 1 required positional argument: 'name'

because the storage is never initialized

**Comment by tumb1er** [comment]
Could you please provide a PR with failing test?

**Comment by xanderim** [comment]
Thanks for the quick reply @tumb1er. Not sure if I can do it but here is the code that doesn't work for me on v0.4.0
```
fs = FileSystemStorage(location=ROOT_DIR)
generator = SitemapGenerator(sitemaps=SITEMAPS, storage=fs, index_url_name='sitemap-index')
generator.generate()
```

**Comment by tumb1er** [comment]
OK, I'll try to look at it in a view days.

**Comment by tumb1er** [comment]
@xanderim could you please check a fix from https://github.com/tumb1er/django-sitemap-generate/tree/fix_import_storage_by_string ?

**Comment by xanderim** [comment]
Hi @tumb1er. Yep,  works for me. Thanks for the fix!
